main: main.cpp InputManager.cpp ItemSpawner.cpp Snake.cpp WindowManager.cpp GateSpawner.cpp
	g++ -o main main.cpp InputManager.cpp ItemSpawner.cpp Snake.cpp WindowManager.cpp GateSpawner.cpp -lncurses -std=c++17
